export const data = [
  {
    id: "507271a19054f77946035eae",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 774",
    status: "warning",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "kB",
      value: 4521829,
    },
    scanning_interval: 600,
  },
  {
    id: "594d8242b165cc197e8d5bcf",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 165",
    status: "down",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "kB",
      value: 2548463,
    },
    scanning_interval: 60,
  },
  {
    id: "1af7cfc1a261bc49514cac0a",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 998",
    status: "down",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "kB",
      value: 5396448,
    },
    scanning_interval: 360,
  },
  {
    id: "e0d8b42f5a48fdb1cd0cf01e",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 300",
    status: "down",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "kB",
      value: 1447375,
    },
    scanning_interval: 480,
  },
  {
    id: "05569de0bff1ce3641116b16",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 176",
    status: "paused",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "kB",
      value: 10213369,
    },
    scanning_interval: 240,
  },
  {
    id: "5eb70f000a144bada8f66c20",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 688",
    status: "down",
    favorite: false,
    since: 1,
    last_measurement: {
      unit: "kB",
      value: 1509954,
    },
    scanning_interval: 360,
  },
  {
    id: "d5e82f471ab3778abfd9f1b3",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 260",
    status: "warning",
    favorite: false,
    since: 1,
    last_measurement: {
      unit: "kB",
      value: 1267118,
    },
    scanning_interval: 180,
  },
  {
    id: "cae97ec3dcb2de8e1ce7d5af",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 468",
    status: "up",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "kB",
      value: 5767732,
    },
    scanning_interval: 360,
  },
  {
    id: "af12dc8b150d8a04bc4dfbfa",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 440",
    status: "down",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "kB",
      value: 8900063,
    },
    scanning_interval: 360,
  },
  {
    id: "4b2f3ba2ea16fc4febfcb4d2",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 141",
    status: "warning",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "kB",
      value: 4652032,
    },
    scanning_interval: 120,
  },
  {
    id: "c8fec60d0d1a9f677eefea2c",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 697",
    status: "warning",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "kB",
      value: 2448409,
    },
    scanning_interval: 480,
  },
  {
    id: "b0dedefcaae5318cc11a2320",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 377",
    status: "paused",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "kB",
      value: 612149,
    },
    scanning_interval: 60,
  },
  {
    id: "7865a931cecc7aa2ce46b03e",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 420",
    status: "up",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "kB",
      value: 7822501,
    },
    scanning_interval: 360,
  },
  {
    id: "d2675d6a5ddd0aeeedb1ca8a",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 613",
    status: "up",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "kB",
      value: 5113303,
    },
    scanning_interval: 420,
  },
  {
    id: "1f1cafcdc8d7733ea6e94b6c",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 350",
    status: "warning",
    favorite: false,
    since: 1,
    last_measurement: {
      unit: "kB",
      value: 540013,
    },
    scanning_interval: 360,
  },
  {
    id: "26afa8d9fac48aafc07ccda7",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 594",
    status: "down",
    favorite: false,
    since: 1,
    last_measurement: {
      unit: "kB",
      value: 91130,
    },
    scanning_interval: 480,
  },
  {
    id: "c92b080a289ab278574fd0ea",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 865",
    status: "warning",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "kB",
      value: 1745852,
    },
    scanning_interval: 540,
  },
  {
    id: "2c054d29cc4b1bcced0ddb67",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 397",
    status: "warning",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "kB",
      value: 9292896,
    },
    scanning_interval: 240,
  },
  {
    id: "fec685082abfe3d8daf3d3fc",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 638",
    status: "down",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "kB",
      value: 1569623,
    },
    scanning_interval: 300,
  },
  {
    id: "f7dd8bbfbfdbd4ebae5fda0f",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 856",
    status: "down",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "kB",
      value: 7984134,
    },
    scanning_interval: 60,
  },
  {
    id: "a67c77ed3fd94aca3ee5def7",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 539",
    status: "warning",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "kB",
      value: 4563876,
    },
    scanning_interval: 180,
  },
  {
    id: "eb15ec15de9fc877df6fcdff",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 261",
    status: "up",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "kB",
      value: 7649168,
    },
    scanning_interval: 60,
  },
  {
    id: "eb4ad6f49de68fc76bd14e27",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 483",
    status: "up",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "kB",
      value: 6619922,
    },
    scanning_interval: 360,
  },
  {
    id: "bcfc02ef453fb9995af88cdf",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 941",
    status: "paused",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "kB",
      value: 3449907,
    },
    scanning_interval: 480,
  },
  {
    id: "fc02e2aff2db34fde81c5ce1",
    kind: "SNMP Traffic",
    name: "Traffic - Ethernet 588",
    status: "down",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "kB",
      value: 6466549,
    },
    scanning_interval: 60,
  },
  {
    id: "2aaad1da839d983cbadd7750",
    kind: "SNMP Load",
    name: "CPU Load - Server 609",
    status: "up",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "%",
      value: 86,
    },
    scanning_interval: 600,
  },
  {
    id: "2cdd67478e0422b2acb4e7ec",
    kind: "SNMP Load",
    name: "CPU Load - Server 841",
    status: "up",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "%",
      value: 14,
    },
    scanning_interval: 420,
  },
  {
    id: "0abcd3ce09f7b404e260e7de",
    kind: "SNMP Load",
    name: "CPU Load - Server 403",
    status: "up",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "%",
      value: 52,
    },
    scanning_interval: 540,
  },
  {
    id: "eab9cfd7aaaa3fba6fc505cb",
    kind: "SNMP Load",
    name: "CPU Load - Server 716",
    status: "paused",
    favorite: false,
    since: 1,
    last_measurement: {
      unit: "%",
      value: 7,
    },
    scanning_interval: 360,
  },
  {
    id: "6ef3aa2de9cde20a0f2ac47a",
    kind: "SNMP Load",
    name: "CPU Load - Server 299",
    status: "down",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "%",
      value: 13,
    },
    scanning_interval: 60,
  },
  {
    id: "bcecad53fe2ebbfab070d11b",
    kind: "SNMP Load",
    name: "CPU Load - Server 514",
    status: "paused",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "%",
      value: 99,
    },
    scanning_interval: 480,
  },
  {
    id: "2b54c36259a1caf4169ebd02",
    kind: "SNMP Load",
    name: "CPU Load - Server 61",
    status: "paused",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "%",
      value: 50,
    },
    scanning_interval: 480,
  },
  {
    id: "eb007ebe9ded9d7adcf0ee23",
    kind: "SNMP Load",
    name: "CPU Load - Server 922",
    status: "down",
    favorite: false,
    since: 4,
    last_measurement: {
      unit: "%",
      value: 19,
    },
    scanning_interval: 120,
  },
  {
    id: "fe8b08b27f2f913ca3a1ac78",
    kind: "SNMP Load",
    name: "CPU Load - Server 284",
    status: "up",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "%",
      value: 25,
    },
    scanning_interval: 600,
  },
  {
    id: "bceb3b1f2eeed6069cf53bea",
    kind: "SNMP Load",
    name: "CPU Load - Server 488",
    status: "paused",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "%",
      value: 79,
    },
    scanning_interval: 480,
  },
  {
    id: "8de5581f0bfa60523c68aec4",
    kind: "SNMP Load",
    name: "CPU Load - Server 296",
    status: "paused",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "%",
      value: 75,
    },
    scanning_interval: 180,
  },
  {
    id: "e17d7ffbe27cdc8a025820de",
    kind: "SNMP Load",
    name: "CPU Load - Server 982",
    status: "warning",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "%",
      value: 88,
    },
    scanning_interval: 180,
  },
  {
    id: "7d8864effc7fdd7b15af20ca",
    kind: "SNMP Load",
    name: "CPU Load - Server 563",
    status: "down",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "%",
      value: 41,
    },
    scanning_interval: 480,
  },
  {
    id: "bc4c3d00e03e30ea3ceebfcb",
    kind: "SNMP Load",
    name: "CPU Load - Server 898",
    status: "down",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "%",
      value: 81,
    },
    scanning_interval: 540,
  },
  {
    id: "b71ce143fca06defedfd8c67",
    kind: "SNMP Load",
    name: "CPU Load - Server 796",
    status: "up",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "%",
      value: 32,
    },
    scanning_interval: 420,
  },
  {
    id: "6a3ef9fe9c56c5f4be87bfe5",
    kind: "SNMP Load",
    name: "CPU Load - Server 274",
    status: "down",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "%",
      value: 85,
    },
    scanning_interval: 300,
  },
  {
    id: "3ed64968cb4ecab6705b65cf",
    kind: "SNMP Load",
    name: "CPU Load - Server 969",
    status: "up",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "%",
      value: 43,
    },
    scanning_interval: 540,
  },
  {
    id: "1efeb6ce0b3eaefab1cea40e",
    kind: "SNMP Load",
    name: "CPU Load - Server 286",
    status: "warning",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "%",
      value: 21,
    },
    scanning_interval: 180,
  },
  {
    id: "4aca6cc691d7de69fbde08ad",
    kind: "SNMP Load",
    name: "CPU Load - Server 669",
    status: "paused",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "%",
      value: 42,
    },
    scanning_interval: 420,
  },
  {
    id: "bffe0acbe3adaafac8bca8b4",
    kind: "SNMP Load",
    name: "CPU Load - Server 360",
    status: "warning",
    favorite: false,
    since: 4,
    last_measurement: {
      unit: "%",
      value: 72,
    },
    scanning_interval: 180,
  },
  {
    id: "a7b7d4f9caa08af3feba9ac1",
    kind: "SNMP Load",
    name: "CPU Load - Server 139",
    status: "down",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "%",
      value: 66,
    },
    scanning_interval: 180,
  },
  {
    id: "f05bf4deb53be56193685402",
    kind: "SNMP Load",
    name: "CPU Load - Server 772",
    status: "warning",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "%",
      value: 56,
    },
    scanning_interval: 600,
  },
  {
    id: "c2d259fbbd2fea4335663305",
    kind: "SNMP Load",
    name: "CPU Load - Server 152",
    status: "warning",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "%",
      value: 34,
    },
    scanning_interval: 120,
  },
  {
    id: "990cbd6d572dc99810a7820a",
    kind: "SNMP Load",
    name: "CPU Load - Server 603",
    status: "up",
    favorite: false,
    since: 1,
    last_measurement: {
      unit: "%",
      value: 97,
    },
    scanning_interval: 360,
  },
  {
    id: "bbc9d6eaeaeceb8d0e9cb3d7",
    kind: "SNMP Load",
    name: "CPU Load - Server 664",
    status: "paused",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "%",
      value: 59,
    },
    scanning_interval: 420,
  },
  {
    id: "eadfeab55ba964a0a309fa8d",
    kind: "Ping",
    name: "unwilling-deer.com",
    status: "warning",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 26.34,
    },
    scanning_interval: 360,
  },
  {
    id: "abd80dcf5dfccbad2ad98e84",
    kind: "Ping",
    name: "unsung-sweatshop.info",
    status: "down",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "msec",
      value: 37.92,
    },
    scanning_interval: 540,
  },
  {
    id: "f6df3c0ede422a58bf003db7",
    kind: "Ping",
    name: "puzzled-hyena.name",
    status: "down",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 38.52,
    },
    scanning_interval: 540,
  },
  {
    id: "ac92bdc2ea73d0abeefc1dfb",
    kind: "Ping",
    name: "distorted-kielbasa.biz",
    status: "up",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "msec",
      value: 13,
    },
    scanning_interval: 360,
  },
  {
    id: "77b6e15b502f0ea0bbff2db4",
    kind: "Ping",
    name: "usable-council.info",
    status: "paused",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 27.96,
    },
    scanning_interval: 600,
  },
  {
    id: "c55d0dd7acf1dec0c2fbe1b4",
    kind: "Ping",
    name: "yummy-bowler.info",
    status: "warning",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 27.58,
    },
    scanning_interval: 420,
  },
  {
    id: "2da8ac8baaed0aa09d4c00cb",
    kind: "Ping",
    name: "grubby-ceramic.org",
    status: "paused",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 40.52,
    },
    scanning_interval: 480,
  },
  {
    id: "37e43b632af27e36be7b96f2",
    kind: "Ping",
    name: "shimmering-countess.org",
    status: "warning",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 29.72,
    },
    scanning_interval: 300,
  },
  {
    id: "d25d992d2feda76b5ef5c41c",
    kind: "Ping",
    name: "little-impostor.info",
    status: "paused",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "msec",
      value: 33.6,
    },
    scanning_interval: 360,
  },
  {
    id: "dfaa04fc4dcfc0b529dbfeae",
    kind: "Ping",
    name: "sentimental-encouragement.com",
    status: "up",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "msec",
      value: 9.02,
    },
    scanning_interval: 300,
  },
  {
    id: "ca267cebd36c40e1f16b3e36",
    kind: "Ping",
    name: "mean-wheel.com",
    status: "down",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "msec",
      value: 37.92,
    },
    scanning_interval: 240,
  },
  {
    id: "9c5a9deb0e0f2cafcbb7f00d",
    kind: "Ping",
    name: "first-cd.info",
    status: "up",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "msec",
      value: 14.9,
    },
    scanning_interval: 180,
  },
  {
    id: "8f72d3d44e8bd5e69fcb51a8",
    kind: "Ping",
    name: "hungry-pressure.com",
    status: "paused",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 11.24,
    },
    scanning_interval: 60,
  },
  {
    id: "701fbb67bc6aa3afa9fa9fbb",
    kind: "Ping",
    name: "superficial-cellar.net",
    status: "paused",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "msec",
      value: 16.14,
    },
    scanning_interval: 180,
  },
  {
    id: "554afbbef4848ead8d2b09b5",
    kind: "Ping",
    name: "spotless-chapel.name",
    status: "down",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "msec",
      value: 22.94,
    },
    scanning_interval: 300,
  },
  {
    id: "dd76b0cedafcc876fca767b7",
    kind: "Ping",
    name: "distinct-someplace.org",
    status: "warning",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "msec",
      value: 33.3,
    },
    scanning_interval: 60,
  },
  {
    id: "5ed5bcc63c3eaa2d4c487f3f",
    kind: "Ping",
    name: "jagged-footrest.biz",
    status: "up",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 44.9,
    },
    scanning_interval: 60,
  },
  {
    id: "3d0da984b0b01eff2eccecc0",
    kind: "Ping",
    name: "untried-pop.name",
    status: "warning",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "msec",
      value: 38.5,
    },
    scanning_interval: 540,
  },
  {
    id: "7cd7abc8c7468e02d5fbb6a8",
    kind: "Ping",
    name: "spotless-exterior.com",
    status: "down",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "msec",
      value: 6.38,
    },
    scanning_interval: 300,
  },
  {
    id: "e78ae0d5f91aaf66c3edb65d",
    kind: "Ping",
    name: "unruly-intent.info",
    status: "paused",
    favorite: false,
    since: 9,
    last_measurement: {
      unit: "msec",
      value: 20.98,
    },
    scanning_interval: 600,
  },
  {
    id: "eeea586719fa5dd5697e60b9",
    kind: "Ping",
    name: "assured-scratch.com",
    status: "down",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 49.84,
    },
    scanning_interval: 480,
  },
  {
    id: "b60c64a4827a1a7f08581daa",
    kind: "Ping",
    name: "pastel-contrail.net",
    status: "paused",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "msec",
      value: 40.66,
    },
    scanning_interval: 300,
  },
  {
    id: "4a58bab2ee9561a67c4ceeec",
    kind: "Ping",
    name: "antique-eggplant.biz",
    status: "up",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 48.62,
    },
    scanning_interval: 480,
  },
  {
    id: "b5a6ceacff1e61a867b8edef",
    kind: "Ping",
    name: "grimy-corral.name",
    status: "up",
    favorite: false,
    since: 8,
    last_measurement: {
      unit: "msec",
      value: 33.44,
    },
    scanning_interval: 120,
  },
  {
    id: "0daab8ebf33268ffaaf0df46",
    kind: "Ping",
    name: "careless-bend.com",
    status: "up",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "msec",
      value: 44.62,
    },
    scanning_interval: 120,
  },
  {
    id: "7afdb750bdde41d22edba031",
    kind: "Ping",
    name: "lost-scratch.com",
    status: "paused",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "msec",
      value: 48.02,
    },
    scanning_interval: 240,
  },
  {
    id: "dedf8e9b96f83b36b6d1ec9d",
    kind: "Ping",
    name: "multicolored-hose.biz",
    status: "paused",
    favorite: false,
    since: 3,
    last_measurement: {
      unit: "msec",
      value: 31.46,
    },
    scanning_interval: 420,
  },
  {
    id: "d1c033ae764d21798f6fbbce",
    kind: "Ping",
    name: "vengeful-yin.info",
    status: "paused",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 32.02,
    },
    scanning_interval: 600,
  },
  {
    id: "0756299e71a93df79a8fbaa4",
    kind: "Ping",
    name: "doting-sock.biz",
    status: "down",
    favorite: true,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 40.66,
    },
    scanning_interval: 480,
  },
  {
    id: "bf55421e08ae0ddbbb0eaedc",
    kind: "Ping",
    name: "unimportant-trench.name",
    status: "up",
    favorite: true,
    since: 4,
    last_measurement: {
      unit: "msec",
      value: 10.9,
    },
    scanning_interval: 420,
  },
  {
    id: "4ed9a24e6ed7bd2f4aa7edec",
    kind: "Ping",
    name: "tricky-unblinking.info",
    status: "warning",
    favorite: false,
    since: 5,
    last_measurement: {
      unit: "msec",
      value: 27.78,
    },
    scanning_interval: 60,
  },
  {
    id: "5cb5fbbcdd2bec7681661ffe",
    kind: "Ping",
    name: "understated-meal.com",
    status: "paused",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "msec",
      value: 46.82,
    },
    scanning_interval: 360,
  },
  {
    id: "bf5a838be0bfb37eeb164b59",
    kind: "Ping",
    name: "devoted-monster.biz",
    status: "down",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 49.14,
    },
    scanning_interval: 600,
  },
  {
    id: "d2bd062adabc21fac8f5c58f",
    kind: "Ping",
    name: "lustrous-chops.biz",
    status: "up",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "msec",
      value: 23.36,
    },
    scanning_interval: 540,
  },
  {
    id: "4cd7cb35c084d55b8d5fdc6c",
    kind: "Ping",
    name: "stingy-warming.biz",
    status: "down",
    favorite: true,
    since: 1,
    last_measurement: {
      unit: "msec",
      value: 8.06,
    },
    scanning_interval: 180,
  },
  {
    id: "00aed5d26b8bf03bfdb679b9",
    kind: "Ping",
    name: "simple-certification.name",
    status: "down",
    favorite: true,
    since: 8,
    last_measurement: {
      unit: "msec",
      value: 47.68,
    },
    scanning_interval: 420,
  },
  {
    id: "f26122a8d0bcd2fdc2c7f4ac",
    kind: "Ping",
    name: "dapper-consistency.com",
    status: "warning",
    favorite: true,
    since: 1,
    last_measurement: {
      unit: "msec",
      value: 3.56,
    },
    scanning_interval: 540,
  },
  {
    id: "172e4e83e52bba1349ab9cbc",
    kind: "Ping",
    name: "impassioned-volleyball.name",
    status: "up",
    favorite: false,
    since: 2,
    last_measurement: {
      unit: "msec",
      value: 3.94,
    },
    scanning_interval: 480,
  },
  {
    id: "fffddfffeece7bc2d05f3cbd",
    kind: "Ping",
    name: "celebrated-desk.biz",
    status: "paused",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 6.96,
    },
    scanning_interval: 360,
  },
  {
    id: "ba250e17d556f4406f7f77fe",
    kind: "Ping",
    name: "shameless-instructor.net",
    status: "warning",
    favorite: true,
    since: 8,
    last_measurement: {
      unit: "msec",
      value: 8.54,
    },
    scanning_interval: 120,
  },
  {
    id: "accab6fcd5b465dbbd0707eb",
    kind: "Ping",
    name: "velvety-fowl.name",
    status: "up",
    favorite: true,
    since: 9,
    last_measurement: {
      unit: "msec",
      value: 48.9,
    },
    scanning_interval: 300,
  },
  {
    id: "ab6e1edadeaacda2ed67be6e",
    kind: "Ping",
    name: "scary-gallery.info",
    status: "down",
    favorite: true,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 21.4,
    },
    scanning_interval: 540,
  },
  {
    id: "2b9a228ef51efbfe8524ac9f",
    kind: "Ping",
    name: "second-barge.net",
    status: "up",
    favorite: true,
    since: 8,
    last_measurement: {
      unit: "msec",
      value: 6,
    },
    scanning_interval: 360,
  },
  {
    id: "eba8d23bf3c7a8efd5dfca07",
    kind: "Ping",
    name: "intrepid-steak.com",
    status: "warning",
    favorite: false,
    since: 7,
    last_measurement: {
      unit: "msec",
      value: 45.14,
    },
    scanning_interval: 600,
  },
  {
    id: "a510d07bedabe52fcf0aed03",
    kind: "Ping",
    name: "circular-porter.net",
    status: "warning",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 31.98,
    },
    scanning_interval: 60,
  },
  {
    id: "d550c95b5b1d3b1b8f56b8ab",
    kind: "Ping",
    name: "torn-sanity.name",
    status: "paused",
    favorite: true,
    since: 1,
    last_measurement: {
      unit: "msec",
      value: 26.72,
    },
    scanning_interval: 540,
  },
  {
    id: "74fc2eb13109e8f6f445eddb",
    kind: "Ping",
    name: "grandiose-puppet.info",
    status: "paused",
    favorite: true,
    since: 2,
    last_measurement: {
      unit: "msec",
      value: 1.24,
    },
    scanning_interval: 420,
  },
  {
    id: "75367672e8ccfe7cef50aa29",
    kind: "Ping",
    name: "austere-netsuke.org",
    status: "warning",
    favorite: false,
    since: 1,
    last_measurement: {
      unit: "msec",
      value: 8.2,
    },
    scanning_interval: 540,
  },
  {
    id: "751d205bb15cacffc9fc462d",
    kind: "Ping",
    name: "unwieldy-blight.name",
    status: "up",
    favorite: false,
    since: 10,
    last_measurement: {
      unit: "msec",
      value: 28.6,
    },
    scanning_interval: 60,
  },
  {
    id: "24400f7fce3bb4051fffa0de",
    kind: "Ping",
    name: "murky-membership.com",
    status: "warning",
    favorite: false,
    since: 6,
    last_measurement: {
      unit: "msec",
      value: 5.92,
    },
    scanning_interval: 180,
  },
];

